title: The Distraction Shield
email: distractionshield.devteam@gmail.com
description: Welcome to The Distraction Shield!
baseurl: "/2017-The-Distraction-Shield"
url: "https://rugsofteng.github.io"
favicon: favicon.ico
github_username:  RUGSoftEng/2017-The-Distraction-Shield

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

exclude: [vendor]
